name: hackathon
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.11
  - fastapi
  - uvicorn
  - o365
  - python-dotenv
  - python-pdfkit
  - pytorch
  - torchvision
  - easyocr
  - pdf2image
  - pillow
  - openai